name: enefty_icons
description: Enefty Icons Pack For Flutter
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: EneftyIcons
      fonts:
        - asset: lib/assets/fonts/icons/EneftyIcons.ttf