name: enefty_icons
description: Flutter repository that contains Enefty Icon Pack. Enefty is an asset repo containing a set of icon assets made by Pickolab Studio and Licensed under CC BY 4.0
repository: https://github.com/omar-hanafy/nft-icons
version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: EneftyIcons
      fonts:
        - asset: lib/assets/fonts/icons/EneftyIcons.ttf