import 'package:flutter/widgets.dart';

class NFTLinearIcon {
  NFTLinearIcon._();

  static const _kFontFam = 'NFTLinearIcon';
  static const String? _kFontPkg = 'nft_icons';

  static const IconData a_3d_cube_scan =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_3d_cube =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_3d_rotate =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_3d_square =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_24_support =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_1 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_square =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additem =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airdrop =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplane_square =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplane =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airpod =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airpods =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_bottom =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_vertically =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_add =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_horizontally =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_book =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_minus =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_tick =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrange_circle =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrange_square_2 =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_3 =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_slash =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_bottom =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_left =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_1 =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_2 =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_2 =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_3 =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_2 =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_1 =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_2 =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_left =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_right =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_swap_horizontal =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_1 =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_2 =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_3 =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_circle =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_square =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio_square =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autobrightness =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_square =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_1 =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_10_seconds =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_15_seconds =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_item =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_2 =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_cross_1 =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_cross =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_happy =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_tick_2 =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_timer =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_tick =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_charging =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_disable =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_empty_1 =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_full =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_half_full =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bezier =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_card_1 =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_card =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_convert =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_refresh =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blend_2 =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blend =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_2 =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_rectangle =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_circle =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_3_square =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_1 =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrange_circle_2 =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_right =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrange_square =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_3 =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_5_seconds =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_empty =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_1 =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blur =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_saved =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_square =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_2 =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_1 =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_2 =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_add =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_remove =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_search =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_tick =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_time =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brifecase_cross =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brifecase_tick =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brifecase_timer =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broom =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_1 =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_3 =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_2 =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bucket_circle =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bucket_square =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_3 =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_4 =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buildings_2 =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buildings =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buliding =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buy_crypto =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_1 =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_2 =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_add =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_circle =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_edit =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_remove =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_search =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_tick =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_add =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_calling =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_incoming =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_minus =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_outgoing =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_received =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_remove =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_slash =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_slash =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candle_2 =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candle =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_add =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_coin =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_edit =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_pos =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_receive =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_remove_1 =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_remove =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_send =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_slash =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_tick_1 =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_tick =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_2 =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_1 =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_2 =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_3 =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_21 =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_square =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_success =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_close =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_export =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_import =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_text =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_tick =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_1 =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_square =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_add =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_change =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_connection =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_cross =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_drizzle =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_fog =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_lightning =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_minus =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_notif =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_plus =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_remove =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_snow =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sunny =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_1 =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_circle =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin_1 =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_swatch =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colorfilter =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colors_square =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData command_square =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData command =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData component =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computing =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData convert_3d_cube =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData convert =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData convertshape_2 =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData convertshape =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_success =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData courthouse =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu_charge =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu_setting =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_1 =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danger =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_2 =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData designtools =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_message =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devices_1 =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devices =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diagram =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamonds =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_down =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_inbox =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_left =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_normal =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_notification =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_right =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_send =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_up =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directbox_default =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directbox_notif =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directbox_receive =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directbox_send =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount_circle =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount_shape =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover_1 =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_1 =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_cloud =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_code_2 =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_code =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_copy =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_download =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_favorite =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_filter =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_forward =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_like =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_previous =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_sketch =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_text_1 =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_text =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_upload =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_circle =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_square =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driver_2 =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driver_refresh =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driver =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driving =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2 =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData element_1 =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData element_2 =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData element_3 =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData element_4 =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData element_equal =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData element_plus =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_happy =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_normal =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_sad =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet_add =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet_change =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet_remove =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet_tick =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet_time =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser_1 =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_1 =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_2 =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_3 =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_drive =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fatrows =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_chart =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_add =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_edit =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_remove =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_search =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_square =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_tick =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finger_cricle =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finger_scan =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firstline =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_2 =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_1 =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_circle_1 =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_circle =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_slash =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_connection =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_circle =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_square =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_5_seconds =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_10_seconds =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_15_seconds =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_item =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_square =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_1 =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_2 =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_3 =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_4 =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_5 =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_add =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_edit =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_export =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_favorite =
      IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_import =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_remove =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_slash =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_tick =
      IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game =
      IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gameboy =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas_station =
      IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_1 =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass =
      IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global_edit =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global_refresh =
      IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global_search =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global =
      IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps_slash =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps =
      IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grammerly =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph =
      IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_1 =
      IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_2 =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_3 =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_4 =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_5 =
      IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_6 =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_7 =
      IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_8 =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_9 =
      IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_edit =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_eraser =
      IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_lock =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1 =
      IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_2 =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_3 =
      IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_4 =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_5 =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_6 =
      IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_7 =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_8 =
      IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_9 =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
      IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happyemoji =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag_1 =
      IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag_down =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag_up =
      IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphone =
      IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health =
      IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_add =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_circle =
      IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_edit =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_remove =
      IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_search =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_slash =
      IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_tick =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy_2 =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy_3 =
      IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy_square_2 =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy_square_3 =
      IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy_square =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy =
      IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_hashtag =
      IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_trend_down =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_trend_up =
      IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_wifi =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_2 =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_1 =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_2 =
      IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_icon =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle =
      IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ios_backspace =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData judge =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kanban =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_square =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_open =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard =
      IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp_1 =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp_charge =
      IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp_on =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp_slash =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language_circle =
      IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language_square =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData level =
      IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifebuoy =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_1 =
      IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_dislike =
      IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_shapes =
      IconData(0xe9c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_tag =
      IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like =
      IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_1 =
      IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_2 =
      IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_21 =
      IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_circle =
      IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_square =
      IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe9cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_add =
      IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_cross =
      IconData(0xe9cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_minus =
      IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_slash =
      IconData(0xe9d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_tick =
      IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 =
      IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_circle =
      IconData(0xe9d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_slash =
      IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login_1 =
      IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login =
      IconData(0xe9d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 =
      IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lovely =
      IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic_star =
      IconData(0xe9dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magicpen =
      IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData main_component =
      IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man =
      IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_1 =
      IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map =
      IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_1 =
      IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_2 =
      IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask =
      IconData(0xe9e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math =
      IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_1 =
      IconData(0xe9e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_2 =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_3 =
      IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_4 =
      IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_21 =
      IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_circle =
      IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize =
      IconData(0xe9ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal_star =
      IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal =
      IconData(0xe9ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_1 =
      IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_board =
      IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_2 =
      IconData(0xe9f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_add_1 =
      IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_add =
      IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_circle =
      IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_edit =
      IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_favorite =
      IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_minus =
      IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_notif =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_programming =
      IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_question =
      IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_remove =
      IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_search =
      IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_square =
      IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_text_1 =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_text =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_tick =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_time =
      IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages_1 =
      IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages_2 =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages_3 =
      IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone_2 =
      IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone_slash_1 =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone_slash =
      IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope =
      IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milk =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mini_music_sqaure =
      IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_cirlce =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_square =
      IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirroring_screen =
      IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile =
      IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_programming =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_2 =
      IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_3 =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_4 =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_add =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_change =
      IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_forbidden =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_recive =
      IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_remove =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_send =
      IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_tick =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_time =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneys =
      IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor_mobbile =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor_recorder =
      IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_2 =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_circle =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_square =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse_1 =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse_circle =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse_square =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_circle =
      IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_dashboard =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_filter =
      IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_library_2 =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_play =
      IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_playlist =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_square_add =
      IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_square_remove =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_square_search =
      IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_square =
      IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music =
      IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicnote =
      IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next =
      IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_1 =
      IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_2 =
      IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_21 =
      IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_add =
      IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_favorite =
      IconData(0xea41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_remove =
      IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_square =
      IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_text =
      IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note =
      IconData(0xea45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_1 =
      IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bing =
      IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_circle =
      IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_favorite =
      IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_status =
      IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xea4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData omega_circle =
      IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData omega_square =
      IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paintbucket =
      IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperclip_2 =
      IconData(0xea4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperclip =
      IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_check =
      IconData(0xea51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_2 =
      IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_square =
      IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path =
      IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circle =
      IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      IconData(0xea56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_add =
      IconData(0xea57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_remove =
      IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_close =
      IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_tool_2 =
      IconData(0xea5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_tool =
      IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xea5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percentage_square =
      IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personalcard =
      IconData(0xea5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet =
      IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharagraphspacing =
      IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_frame =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_add =
      IconData(0xea62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle =
      IconData(0xea63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_cricle =
      IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_remove =
      IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xea66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presention_chart =
      IconData(0xea67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData previous =
      IconData(0xea68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer_slash =
      IconData(0xea69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer =
      IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_2user =
      IconData(0xea6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_add =
      IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle =
      IconData(0xea6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_delete =
      IconData(0xea6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_remove =
      IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_tick =
      IconData(0xea70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile =
      IconData(0xea71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData programming_arrow =
      IconData(0xea72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData programming_arrows =
      IconData(0xea73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_down_circle =
      IconData(0xea74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_down_square =
      IconData(0xea75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_down =
      IconData(0xea76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_up_circle =
      IconData(0xea77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_up_square =
      IconData(0xea78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_up =
      IconData(0xea79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radar_1 =
      IconData(0xea7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radar_2 =
      IconData(0xea7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radar =
      IconData(0xea7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio =
      IconData(0xea7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ram_2 =
      IconData(0xea7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ram =
      IconData(0xea7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ranking_1 =
      IconData(0xea80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ranking =
      IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_1 =
      IconData(0xea82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_2_1 =
      IconData(0xea83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_2 =
      IconData(0xea84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_add =
      IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_discount =
      IconData(0xea86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_disscount =
      IconData(0xea87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_edit =
      IconData(0xea88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_item =
      IconData(0xea89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_minus =
      IconData(0xea8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_search =
      IconData(0xea8b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_square =
      IconData(0xea8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_text =
      IconData(0xea8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt =
      IconData(0xea8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive_square_2 =
      IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive_square =
      IconData(0xea90, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData received =
      IconData(0xea91, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record_circle =
      IconData(0xea92, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record =
      IconData(0xea93, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recovery_convert =
      IconData(0xea94, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo =
      IconData(0xea95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_2 =
      IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_circle =
      IconData(0xea97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_left_square =
      IconData(0xea98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_right_square =
      IconData(0xea99, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_square_2 =
      IconData(0xea9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xea9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_circle =
      IconData(0xea9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat =
      IconData(0xea9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeate_music =
      IconData(0xea9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeate_one =
      IconData(0xea9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reserve =
      IconData(0xeaa0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left_1 =
      IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left =
      IconData(0xeaa2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right_1 =
      IconData(0xeaa3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right =
      IconData(0xeaa4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route_square =
      IconData(0xeaa5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routing_2 =
      IconData(0xeaa6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routing =
      IconData(0xeaa7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData row_horizontal =
      IconData(0xeaa8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData row_vertical =
      IconData(0xeaa9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler =
      IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler_pen =
      IconData(0xeaab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safe_home =
      IconData(0xeaac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_2 =
      IconData(0xeaad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_add =
      IconData(0xeaae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_minus =
      IconData(0xeaaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_remove =
      IconData(0xeab0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan_barcode =
      IconData(0xeab1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan =
      IconData(0xeab2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanner =
      IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanning =
      IconData(0xeab4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissor_1 =
      IconData(0xeab5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissor =
      IconData(0xeab6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screenmirroring =
      IconData(0xeab7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll =
      IconData(0xeab8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_favorite_1 =
      IconData(0xeab9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_favorite =
      IconData(0xeaba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_normal_1 =
      IconData(0xeabb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_normal =
      IconData(0xeabc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_status_1 =
      IconData(0xeabd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_status =
      IconData(0xeabe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_zoom_in_1 =
      IconData(0xeabf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_zoom_in =
      IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_zoom_out_1 =
      IconData(0xeac1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_zoom_out =
      IconData(0xeac2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_card =
      IconData(0xeac3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_safe =
      IconData(0xeac4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_time =
      IconData(0xeac5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_user =
      IconData(0xeac6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security =
      IconData(0xeac7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_1 =
      IconData(0xeac8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_2 =
      IconData(0xeac9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_sqaure_2 =
      IconData(0xeaca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_square =
      IconData(0xeacb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xeacc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_2 =
      IconData(0xeacd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_3 =
      IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_4 =
      IconData(0xeacf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_5 =
      IconData(0xead0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting =
      IconData(0xead1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xead2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shapes_1 =
      IconData(0xead3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shapes =
      IconData(0xead4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xead5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_cross =
      IconData(0xead6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_search =
      IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_security =
      IconData(0xead8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_slash =
      IconData(0xead9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_tick =
      IconData(0xeada, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xeadb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship =
      IconData(0xeadc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_add =
      IconData(0xeadd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_remove =
      IconData(0xeade, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop =
      IconData(0xeadf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag =
      IconData(0xeae0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart =
      IconData(0xeae1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar_bottom =
      IconData(0xeae2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar_left =
      IconData(0xeae3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar_right =
      IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar_top =
      IconData(0xeae5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signpost =
      IconData(0xeae6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simcard_1 =
      IconData(0xeae7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simcard_2 =
      IconData(0xeae8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simcard =
      IconData(0xeae9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData size =
      IconData(0xeaea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slash =
      IconData(0xeaeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider_horizontal_1 =
      IconData(0xeaec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider_horizontal =
      IconData(0xeaed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider_vertical_1 =
      IconData(0xeaee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider_vertical =
      IconData(0xeaef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider =
      IconData(0xeaf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallcaps =
      IconData(0xeaf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smart_car =
      IconData(0xeaf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smart_home =
      IconData(0xeaf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smileys =
      IconData(0xeaf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_edit =
      IconData(0xeaf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_notification =
      IconData(0xeaf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_search =
      IconData(0xeaf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_star =
      IconData(0xeaf8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_tracking =
      IconData(0xeaf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms =
      IconData(0xeafa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xeafb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound =
      IconData(0xeafc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker =
      IconData(0xeafd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speedometer =
      IconData(0xeafe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 =
      IconData(0xeaff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_slash =
      IconData(0xeb00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xeb01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_up =
      IconData(0xeb02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status =
      IconData(0xeb03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticker =
      IconData(0xeb04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stickynote =
      IconData(0xeb05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_circle =
      IconData(0xeb06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xeb07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData story =
      IconData(0xeb08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strongbox_2 =
      IconData(0xeb09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strongbox =
      IconData(0xeb0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subtitle =
      IconData(0xeb0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_1 =
      IconData(0xeb0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_fog =
      IconData(0xeb0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun =
      IconData(0xeb0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_2 =
      IconData(0xeb0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_cross =
      IconData(0xeb10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_right =
      IconData(0xeb11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_user =
      IconData(0xeb12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xeb13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_square =
      IconData(0xeb14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task =
      IconData(0xeb15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teacher =
      IconData(0xeb16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_block =
      IconData(0xeb17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_bold =
      IconData(0xeb18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_italic =
      IconData(0xeb19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_underline =
      IconData(0xeb1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text =
      IconData(0xeb1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textalign_center =
      IconData(0xeb1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textalign_justifycenter =
      IconData(0xeb1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textalign_justifyleft =
      IconData(0xeb1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textalign_justifyright =
      IconData(0xeb1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textalign_left =
      IconData(0xeb20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textalign_right =
      IconData(0xeb21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_circle =
      IconData(0xeb22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_square =
      IconData(0xeb23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_2 =
      IconData(0xeb24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_discount =
      IconData(0xeb25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_expired =
      IconData(0xeb26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_star =
      IconData(0xeb27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket =
      IconData(0xeb28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer_1 =
      IconData(0xeb29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer_pause =
      IconData(0xeb2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer_start =
      IconData(0xeb2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer =
      IconData(0xeb2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off_circle =
      IconData(0xeb2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off =
      IconData(0xeb2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on_circle =
      IconData(0xeb2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on =
      IconData(0xeb30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trade =
      IconData(0xeb31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_minus =
      IconData(0xeb32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate =
      IconData(0xeb33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xeb34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree =
      IconData(0xeb35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_down =
      IconData(0xeb36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_up =
      IconData(0xeb37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle =
      IconData(0xeb38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_remove =
      IconData(0xeb39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_tick =
      IconData(0xeb3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_time =
      IconData(0xeb3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trush_square =
      IconData(0xeb3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo =
      IconData(0xeb3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlimited =
      IconData(0xeb3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add =
      IconData(0xeb3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xeb40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_cirlce_add =
      IconData(0xeb41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit =
      IconData(0xeb42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_minus =
      IconData(0xeb43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_octagon =
      IconData(0xeb44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_remove =
      IconData(0xeb45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_search =
      IconData(0xeb46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_square =
      IconData(0xeb47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_tag =
      IconData(0xeb48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_tick =
      IconData(0xeb49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xeb4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verify =
      IconData(0xeb4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_add =
      IconData(0xeb4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_circle =
      IconData(0xeb4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_horizontal =
      IconData(0xeb4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_octagon =
      IconData(0xeb4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_play =
      IconData(0xeb50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_remove =
      IconData(0xeb51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_slash =
      IconData(0xeb52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_square =
      IconData(0xeb53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_tick =
      IconData(0xeb54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_time =
      IconData(0xeb55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_vertical =
      IconData(0xeb56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      IconData(0xeb57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice_cricle =
      IconData(0xeb58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice_square =
      IconData(0xeb59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_cross =
      IconData(0xeb5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_high =
      IconData(0xeb5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_low_1 =
      IconData(0xeb5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_low =
      IconData(0xeb5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute =
      IconData(0xeb5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_slash =
      IconData(0xeb5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up =
      IconData(0xeb60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_1 =
      IconData(0xeb61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_2 =
      IconData(0xeb62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_3 =
      IconData(0xeb63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_add_1 =
      IconData(0xeb64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_add =
      IconData(0xeb65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_check =
      IconData(0xeb66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_minus =
      IconData(0xeb67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_money =
      IconData(0xeb68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_remove =
      IconData(0xeb69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_search =
      IconData(0xeb6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet =
      IconData(0xeb6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_2 =
      IconData(0xeb6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch_status =
      IconData(0xeb6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch =
      IconData(0xeb6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_1 =
      IconData(0xeb6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight =
      IconData(0xeb70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_square =
      IconData(0xeb71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi =
      IconData(0xeb72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind_2 =
      IconData(0xeb73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind =
      IconData(0xeb74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman =
      IconData(0xeb75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
