name: enefty_icons_preview
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  enefty_icons: ^1.0.7
  dart_helper_utils: ^5.1.0
  flutter_helper_utils: ^8.0.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/github.svg

